### ISSUE TITLE
Cirrus CS35L41 on UX3402 ASUS Laptop

### ISSUE THREAD

**Issue by ritchse** [CirrusLogic/linux-firmware#8]
Hello! I've been struggling trying to make the speakers work on my Zenbook UX3402ZA_UX3402ZA. I was wondering what's the state of the issue since information in the web is really sparse. I've tried some patches I've found online to no avail. I've also read that "Cirrus said we have to wait for ASUS to make a BIOS update" but these comments show no source so I prefer asking here.

Thanks for taking the time to read!

**Comment by speedy01** [comment]
same issue - adding comment to follow

**Comment by speedy01** [comment]
@stefdb

**Comment by stuhenderson** [comment]
Hi,
Support for the UX3402 was upstreamed last year, and looks like it has made its way into the 22.10 kernel quite recently.
Linux and our driver do however require the presence of certain ACPI entries in order to function, so you may require a BIOS update before the sound will work.  Unfortunately we don't have schedule information for when these will be released for each model and would recommend contacting the manufacturer.
You should also make sure your linux-firmware repo/package is up to date to ensure full performance.
Thanks,
Stu

**Comment by speedy01** [comment]
@stuhenderson 
Thank you for your reply. hopefully asus will provide the required bios update.  Its current version, 310, doesn't seem to work.. I did see that @stefdb submitted some patches to use the acpi companion that might help address the issue in the meantime. They have not been accepted yet. It doesn't patch to the older kernel either.. I assume its due to previous updates also not in the 5.19 kernel.  As stated above, I was hopeful for a dkms!  Thank you again for your time!

**Comment by ritchse** [comment]
@stuhenderson thank you so much for keeping us informed about the issue !

**Comment by fermino** [comment]
In case that the BIOS update is not shipped by Asus (which seems to be the case as they said they only support Windows). Would it be possible to add a quirk for the laptop model to override the ACPI propierties?

Thank you!

**Comment by speedy01** [comment]
may or may not be related, but the mic doesn't work for me on the 3.5mm jack

**Comment by socketpair** [comment]
Some great news!
@stuhenderson https://superuser.com/questions/1719920/no-sound-from-internal-speakers-on-laptop-but-headphone-jack-and-hdmi-works

**Comment by openarun** [comment]
@socketpair , in my experience, I tried everything in that, none worked for UX3402.

**Comment by ritchse** [comment]
> @socketpair , in my experience, I tried everything in that, none worked for UX3402.

@openarun same here, that's actually why I started this issue too.

**Comment by stuhenderson** [comment]
@fermino , @socketpair : Unfortunately, due to technical limitations within the kernel, it is not possible to support all laptops using quirks.  Laptops should be updated to contain the appropriate ACPI which should hopefully be supported in a future bios update.

@speedy01 : The 3.5mm jack is unrelated to the audio amp.  You will need to speak to whoever is providing the codec on that laptop.

@ritchse , @socketpair : I would strongly discourage using random patches written without knowledge of the laptop configuration.  Making random changes like that may result in damage to your device.

**Comment by socketpair** [comment]
@stuhenderson 

I understand you. But possibly you may help in fighting against Asus. They officially say that Linux is not a correct usage condition on the device.

I don't know if it is important. But I found this:

```
$ sudo acpidump  | fgrep -i CSC3551
   69BB0: 0D 43 53 43 33 35 35 31 00 08 5F 53 55 42 0D 31  .CSC3551.._SUB.1
```

Possibly they have something in ACPI, but we should read it from another place or so.

**Comment by ritchse** [comment]
@socketpair @(everyone else) I opened this issue just to get first-hand information about the bug. Please don't keep bothering devs here, they're professionals doing their job and I doubt we could provide any information that they don't have access to, unless they ask for our testing or something like that. I don't think they'll have any particular interests in "fighting against ASUS". If anything we could all try to send emails to ASUS customer service or any other channels we find. But don't think devs here should be fixing ASUS faults. 

@stuhenderson Cheers and thank you so much for keeping us informed and answering all our questions, and for the work that you do of course. Feel free to block commenting on this issue if needed.

**Comment by bdandy** [comment]
For those who affected:

Asus probably won't release fixed bios unless they give official Linux support. 
Having those `_DSD` properties are required only for Linux driver.

[Kernel documentation](https://www.kernel.org/doc/Documentation/acpi/gpio-properties.txt) says that driver should provide `_CRS` fallback.

So patching `dsdt` actually solves issue with missing sound on UX3402, but to work it out from the box we need gpio pin map.

Additionally there is issue with patched `dsdt` - you can't use 100% of volume.
Looking for more fixes.

**Comment by socketpair** [comment]
@bdandy could you please give exact steps to get sound working on this laptop ?
